export const WORKCODE = "workcode";
export const USER = "user";
export const SYSTEM_STEIING = "system-setting";
export const QUEUE = "queue";
export const PAUSEREASON = "pause-reason";
export const LOGOUT = "logout";
export const EXTENSION = "extension";
export const FileUpload = "upload/audio";
export const UPDATEPASSWORD = "updatePassword";
export const IVR = "api/ivr"
// export const IVR = "api/ivr"